const assert=require('node:assert/strict'),fs=require('node:fs');
module.exports=async(browser,base)=>{
 const context=await browser.newContext(),page=await context.newPage(),errors=[],midis=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('.mid'))midis.push(r.url());});
 try{
  await page.addInitScript(()=>{window.sent=[];window.ports=new Map(['band','drums'].map(id=>[id,{id,name:id,state:'connected',send:(data,t)=>sent.push({id,data:[...data],t}),clear:()=>sent.push({id,clear:true})}]));window.access={outputs:ports};Object.defineProperty(navigator,'requestMIDIAccess',{value:async()=>access});});
  await page.goto(base+'/#/repertoire');await page.waitForSelector('.tracks');assert.equal(await page.locator('nav.top a').allTextContents().then(x=>x.slice(1,4).join(',')),'Kurs,Repertoire,Theorie');
  for(const role of ['guitar','keys']){await page.goto(base+'/#/repertoire/'+role);await page.waitForSelector('.phase');assert.equal(await page.locator('.phase').count(),6);for(let grade=0;grade<6;grade++){await page.goto(base+'/#/repertoire/'+role+'/'+grade);await page.waitForSelector('.unit');assert.equal(await page.locator('.unit').count(),5);}}
  const catalog=JSON.parse(fs.readFileSync('data/repertoire.json'));
  for(const lang of ['de','en']){await page.selectOption('#language',lang);for(const role of ['guitar','keys'])for(const piece of catalog.pieces){await page.goto(base+'/#/piece/'+role+'/'+piece.id);await page.waitForSelector('#repertoire-piece[data-ready]');assert.equal(await page.locator('h1').innerText(),piece.title);assert(!/undefined|NaN/.test(await page.locator('main').innerText()),piece.id+role);assert.equal(await page.locator('.rep-section').count(),piece.sections.length);assert(await page.locator('svg.score').count()>0);assert.equal(await page.locator('.rep-downloads a').first().getAttribute('href'),encodeURI(piece.midi));const pdf=await page.locator('a[download]').nth(1).getAttribute('href');assert((await page.request.get(base+'/'+pdf)).ok());}}
  await page.goto(base+'/#/piece/guitar/r0-1');await page.waitForSelector('#repertoire-piece[data-ready]');await page.check('[data-done]');await page.locator('details.log summary').click();await page.locator('form input').fill('<script>practice</script>');await page.locator('form button').click();assert.equal(await page.locator('.rep-log script').count(),0);await page.reload();await page.waitForSelector('#repertoire-piece[data-ready]');assert(await page.isChecked('[data-done]'));assert.match(await page.locator('details.log ul').textContent(),/<script>/);
  await page.goto(base+'/#/piece/keys/r0-1');await page.waitForSelector('#repertoire-piece[data-ready]');assert(!await page.isChecked('[data-done]'),'progress is independent by instrument');await page.goto(base+'/#/log');await page.waitForSelector('.logt');assert.equal(await page.locator('.logt a[href="#/piece/guitar/r0-1"]').count(),1);
  await page.goto(base+'/#/midi');await page.waitForSelector('#connect');await page.click('#connect');await page.waitForSelector('#output option[value=band]',{state:'attached'});await page.selectOption('#output','band');await page.selectOption('[data-midi-route="9"]','drums');
  for(const role of ['guitar','keys']){await page.goto(base+'/#/piece/'+role+'/r0-4');await page.waitForSelector('#repertoire-piece[data-ready]');await page.selectOption('#rep-output','midi');await page.uncheck('#rep-count');await page.evaluate(()=>sent=[]);await page.locator('[data-transport=practice]').click();await page.waitForTimeout(250);const out=await page.evaluate(()=>sent);const own=role==='guitar'?6:3,other=role==='guitar'?3:6;assert(!out.some(e=>e.data?.[0]===(144|own)));assert(out.some(e=>e.id==='band'&&e.data?.[0]===(144|other)));assert(out.some(e=>e.id==='band'&&e.data?.[0]===149));assert(out.some(e=>e.id==='drums'&&e.data?.[0]===153));await page.locator('[data-transport=practice]').click();assert((await page.evaluate(()=>sent)).some(e=>e.data?.[1]===120));}
  await page.setViewportSize({width:390,height:844});for(const id of ['r0-1','r3-3','r4-3','r4-4','r5-5'])for(const role of ['guitar','keys']){await page.goto(base+'/#/piece/'+role+'/'+id);await page.waitForSelector('#repertoire-piece[data-ready]');await page.check('#rep-aids');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),id+role+' mobile overflow');}
  await page.screenshot({path:'test-results/repertoire-mobile.png',fullPage:true});await page.goto(base+'/#/credits');await page.waitForSelector('h1');for(const href of await page.locator('main a').evaluateAll(es=>es.map(e=>e.getAttribute('href'))))assert((await page.request.get(base+'/'+href)).ok(),href);assert.equal(await page.locator('a[href*="piano/credits"]').count(),0);assert.deepEqual(errors,[]);
  console.log('PASS 30 pieces × 2 parts × 2 languages, 60 PDF links, MIDI channel/port mix, per-part progress, mobile notation and central licenses');
 }finally{await context.close();}
};
