const assert=require('node:assert/strict');
module.exports=async(browser,base)=>{
 const context=await browser.newContext(),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('.sf2'))requests.push(r.url());});
 try{
  await page.goto(base+'/#/unit/ku0-1');await page.waitForSelector('.listen');assert.equal(requests.length,0,'bank loads only on playback');
  let release;const gate=new Promise(r=>release=r);await page.route('**/*.sf2',async r=>{await gate;await r.continue();});
  await page.locator('.listen').first().click();await page.waitForFunction(()=>document.querySelector('.listen').dataset.playing==='loading');await page.locator('.listen').first().click();release();
  await page.waitForFunction(()=>!!AM.soundfont.engine);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>AM.soundfont.engine.synth.voiceCount),0);assert.equal(await page.locator('.listen[data-playing]').count(),0);await page.unroute('**/*.sf2');
  await page.evaluate(()=>{window.attacks=[];AM.soundfont.engine.synth.eventHandler.addEvent('noteOn','test',e=>attacks.push({...e,time:AM.soundfont.engine.context.currentTime}));const {context,gain}=AM.soundfont.engine;window.analyser=context.createAnalyser();gain.connect(analyser);window.rms=()=>{const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length);};});
  await page.locator('.listen').first().click();await page.waitForFunction(()=>attacks.length>0&&rms()>.0001);await page.locator('.listen').first().click();await page.waitForTimeout(150);assert(await page.evaluate(()=>rms()<1e-7));
  await page.evaluate(async()=>{attacks=[];const play=await AM.audio.prepare([{midi:60,velocity:80,t:.1,dur:.1}]);play(.5,()=>{throw Error('loop ended');});});
  await page.waitForFunction(()=>attacks.length>=4);const times=await page.evaluate(()=>attacks.map(n=>n.time));for(let i=1;i<times.length;i++)assert(Math.abs(times[i]-times[i-1]-.5)<.08,'loop includes silence and lasts full form');await page.evaluate(()=>AM.audio.silence());await page.waitForTimeout(80);const count=await page.evaluate(()=>attacks.length);await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>attacks.length),count,'stop cancels future loop attacks');assert(await page.evaluate(()=>rms()<1e-7));
  await page.evaluate(async()=>{attacks=[];const seq=AM.midi.decode(AM.midi.notes([{midi:60,velocity:80,t:0,dur:.1}],.4)),bytes=AM.midi.excerpt(seq,{countIn:1,pulse:.2});await AM.soundfont.play(bytes,{loop:true,loopStart:.2});});
  await page.waitForFunction(()=>attacks.filter(n=>n.channel===3).length>=4);assert.equal(await page.evaluate(()=>attacks.filter(n=>n.channel===9&&n.midiNote===37).length),1,'count-in occurs once');await page.evaluate(()=>AM.audio.silence());
  assert.equal(requests.length,1,'bank load is shared and cached');
  await page.goto(base+'/#/piece/guitar/r1-4');await page.waitForSelector('#repertoire-piece[data-ready]');await page.uncheck('#rep-count');await page.locator('[data-transport=practice]').click();await page.waitForFunction(()=>AM.soundfont.engine?.synth.midiChannels[6].systemParameters.isMuted&&AM.soundfont.currentTime>.2);
  assert.equal(await page.evaluate(()=>AM.soundfont.engine.synth.midiChannels[3].systemParameters.gain),1);await page.selectOption('#rep-guide','0.25');await page.waitForFunction(()=>AM.soundfont.engine.synth.midiChannels[6].systemParameters.gain===.25);assert.equal(await page.evaluate(()=>AM.soundfont.engine.synth.midiChannels[6].systemParameters.isMuted),false);
  await page.goto(base+'/#/piece/keys/r1-4');await page.waitForSelector('#repertoire-piece[data-ready]');await page.uncheck('#rep-count');await page.locator('[data-transport=practice]').click();await page.waitForFunction(()=>AM.soundfont.engine?.synth.midiChannels[3].systemParameters.isMuted&&AM.soundfont.currentTime>.2);assert.equal(await page.evaluate(()=>AM.soundfont.engine.synth.midiChannels[6].systemParameters.gain),1);await page.goto(base+'/#/theory');await page.waitForTimeout(200);assert(await page.evaluate(()=>AM.soundfont.engine.gain.gain.value===0));
  assert.deepEqual(errors,[]);
  const failed=await browser.newContext(),retry=await failed.newPage();try{await retry.route('**/*.sf2',r=>r.fulfill({status:503,body:'unavailable'}));await retry.goto(base+'/#/unit/ku0-1');await retry.waitForSelector('.listen');await retry.locator('.listen').first().click();await retry.waitForFunction(()=>document.querySelector('.preview-status').textContent.includes('nicht geladen'));await retry.unroute('**/*.sf2');await retry.locator('.listen').first().click();await retry.waitForFunction(()=>AM.soundfont.engine?.synth.voiceCount>0);}finally{await failed.close();}
  console.log('PASS SoundFont lazy loading, cancellation, retry, native audio, full-form loops, single count-in, stop and practice mix');
 }finally{await context.close();}
};
